name: Scrape Service Status/ Outage Data

on:
  schedule:
    # Every 5 minutes (UTC)
    - cron: '*/5 * * * *'
  workflow_dispatch:  # allows manual triggering from the GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Debug Environment
        run: |
          echo "Checking environment variables (values hidden)"
          env | grep SUPABASE || echo "No SUPABASE variables found"        

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use whatever version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scrape_service_status.py

      - name: Show timestamp
        run: echo "Scraped at $(date -u)"